### ISSUE TITLE
which_sbt preferentially uses ./sbt when /usr/local/bin/sbt is needed in CI environment

### ISSUE THREAD

**Issue by lynnju** [CommBank/ci2#19]
lib-ci's which_sbt function is executing ./sbt directly instead of calling through the CI environment sbt runner wrapper at /usr/local/bin/sbt. This results in SBT_LAUNCH_REPO and SBT_LAUNCH_DIR environment variables not being respected which results in errors such as the build being unable to publish or use any other ci2 functionality which depends on sbt. Builds which have cached the sbt launcher do not appear to be affected but will be once the launcher version changes or if they are unable to use the default typesafe repo to get the launcher.

**Comment by lynnju** [comment]
I'm developing a fix right now

**Comment by lynnju** [comment]
Workaround is to set SBT=/usr/local/bin/sbt in the drone.yml or respective build file

**Comment by lynnju** [comment]
PR #20 adds a new flag SBT_PREFER_SYSTEM_SBT_IF_AVAILABLE which first looks on PATH for ```sbt``` using which (standard logic, as before) and uses it if it's available. Otherwise, the system falls back on ```./sbt```, if it is available. If it is not available, the routine exits with an error condition as before.

**Comment by lynnju** [comment]
I recognise that the flag is a tad verbose and am more the happy to take shorter but still meaningful suggestions.

**Comment by rbuckland** [comment]
Shouldn't your codebase be using ``./sbt`` always and not a CI ``/usr/local/bin/sbt`` version ?
What is the CI locally installed wrapper giving you that the repo supplied one doesn't ?

**Comment by lynnju** [comment]
Addressed by #23
