### ISSUE TITLE
ci to ci2 upgrade guide

### ISSUE THREAD

**Issue by triggerNZ** [CommBank/ci2#27]
Right now, (at least to me) it is unclear what the correspondence between `ci` and `ci2` commands is. 

Even a table that maps common commands would be useful

**Comment by andynygard** [comment]
Not quite an upgrade guide but the README has since been updated to describe how to use `ci2` from scratch in travis.

**Comment by rbuckland** [comment]
👍

**Comment by triggerNZ** [comment]
Looks good to me. I'll leave it to you guys to close this :+1:

**Comment by rbuckland** [comment]
doco good so closing.
