### ISSUE TITLE
Version number is not consistent between deployment and creation of the github pages

### ISSUE THREAD

**Issue by stephanh** [CommBank/ci2#35]
sbt-ci-build-doc uses a version number with a more recent timestamp than the version number used by sbt-ci-deploy.

**Comment by stephanh** [comment]
I think this is caused because `sbt-ci-build-doc.sh` calls `Version_Get` which returns a new timestamped version and so does `sbt-ci-setup-version,sh`.

**Comment by andynygard** [comment]
May be related, uniform's [published version](https://commbank.github.io/uniform/index.html) is currently ''.
