### ISSUE TITLE
sbt-ci-setup.sh fails on fork due to lack of access to environment variables

### ISSUE THREAD

**Issue by triggerNZ** [CommBank/ci2#36]
If I have a fork, and raise a PR from it, `sbt-ci-setup.sh` fails with `unbound variable: ARTIFACTORY_USER`. This is due to encrypted variables not being available to forks.

The old `ci` had the following:

``` shell
# Only require that the ARTIFACTORY_PASSWORD is set on master to enable PR.
if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    set -u
fi;
```

That worked but was clunky.

Seeing that `sbt-ci-setup.sh` is usually the first part of a build, and we want PRs from forks to build (but obviously not release), I suggest only doing `set -u` if `TRAVIS_SECURE_ENV_VARS == "true"`, i.e. we are not on a fork

**Comment by toddmowen** [comment]
`TRAVIS_SECURE_ENV_VARS` is nice, but ci2 tries to support both Travis and Drone, and the latter has a [different approach](http://readme.drone.io/usage/secrets/) to secrets.

As alluded to [here](https://github.com/CommBank/ci2/issues/39#issuecomment-241716829), on Travis we can only support PRs from forks if all the project's dependencies are public artifacts. I'm not sure how feasible it is to check this condition.

It may be easiest just to reject pull requests from forks, but provide a more useful error message than the current one.
