### ISSUE TITLE
Support pull requests from forks

### ISSUE THREAD

**Issue by toddmowen** [CommBank/ci2#39]
Travis will not set secret vars (e.g. `ARTIFACTORY_USERNAME`) when the branch being merged is from a fork of the repo. ci2 should still allow such branches to be built (since publishing artifacts will be skipped anyway).

For example, CommBank/dataproducts.common#45 is a PR based on the branch [krishnadasmallya/dataproducts.common:correctJobIdPartition](https://github.com/krishnadasmallya/dataproducts.common/tree/correctJobIdPartition). The build errors out with:

```
ci/sbt-ci-setup.sh: line 25: ARTIFACTORY_USERNAME: unbound variable
```

**Comment by stephanh** [comment]
Given how Travis treats secrets I'm not sure how we can provide the password to pull private dependencies from Artifactory.

**Comment by toddmowen** [comment]
Good point. In that case we should (explicitly) not support pull requests from forks of private repos. A better error message might be:

```
ERROR: Pull requests are not supported from a fork of a private repo.
Please push your changes to the main repo and create a new pull request.
```

For builds in public repos (or equivalently, builds on travis-ci.org) we need to support this use case, because it's the only way that somebody external to CommBank can submit a PR. Also, for public repos we should not use credentials to pull dependencies, because it would be a bug for a public repo to depend on non-public dependencies.

**Comment by toddmowen** [comment]
Duplicate of #38
