### ISSUE TITLE
Rename scripts to .sh (from .bsh); move to src/main/sh and src/test/sh

### ISSUE THREAD

**Issue by afcowie** [CommBank/ci2#6]
## Use of .bsh as extension for shell scripts is bizarre

Shell scripts, by fairly universal convention, have the file extension `.sh`. The fact that you're writing scripts which depend on Bash features deliberately is not unusual, but appropriately guarded by your use of 

```shell
#!/bin/bash
```
in the hash bang line.

## Standardise src layout

In keeping with common layouts

Have scripts in ``src/main/sh``
and tests in       ``src/test/sh``

**Comment by rbuckland** [comment]
Agree - we also commented on the same internally - I haven't got around to correcting it. Happy to have  PR. Else it is on my list

**Comment by rbuckland** [comment]
#13 resolved it.
